

BARRIOS_COMAYAGUA: dict[str, dict] = {
    # ── Barrios históricos ──────────────────────────────────────────────────────
    "BARRIO ABAJO":                  {"poblacion": 5131, "hogares": 1212, "viviendas_ocupadas": 1195, "hacinamiento": 3.90},
    "BARRIO ARRIBA":                 {"poblacion": 8566, "hogares": 2034, "viviendas_ocupadas": 1976, "hacinamiento": 3.87},
    "BARRIO CABAÑAS":                {"poblacion": 5465, "hogares": 1248, "viviendas_ocupadas": 1216, "hacinamiento": 4.09},
    "BARRIO INDEPENDENCIA":          {"poblacion": 4985, "hogares": 1102, "viviendas_ocupadas": 1094, "hacinamiento": 3.84},
    "BARRIO LA CARIDAD":             {"poblacion":  738, "hogares":  176, "viviendas_ocupadas":  176, "hacinamiento": 3.30},
    "BARRIO LA JOYA":                {"poblacion": 1036, "hogares":  250, "viviendas_ocupadas":  242, "hacinamiento": 3.64},
    "BARRIO LA ZARCITA":             {"poblacion": 1192, "hogares":  283, "viviendas_ocupadas":  276, "hacinamiento": 3.77},
    "BARRIO LOS LIRIOS":             {"poblacion": 1868, "hogares":  466, "viviendas_ocupadas":  456, "hacinamiento": 3.59},
    "BARRIO LOURDES":                {"poblacion": 1254, "hogares":  288, "viviendas_ocupadas":  282, "hacinamiento": 3.69},
    "BARRIO SAN ANTONIO DE LA SABANA":{"poblacion": 4470, "hogares":  991, "viviendas_ocupadas":  967, "hacinamiento": 3.93},
    "BARRIO SAN BLAS":               {"poblacion": 3548, "hogares":  773, "viviendas_ocupadas":  755, "hacinamiento": 4.33},
    "BARRIO SAN FRANCISCO":          {"poblacion":  415, "hogares":   99, "viviendas_ocupadas":   96, "hacinamiento": 3.46},
    "BARRIO SAN JOSE":               {"poblacion": 1035, "hogares":  233, "viviendas_ocupadas":  233, "hacinamiento": 3.81},
    "BARRIO SAN PABLO":              {"poblacion":  477, "hogares":  113, "viviendas_ocupadas":  111, "hacinamiento": 3.13},
    "BARRIO SAN RAMON":              {"poblacion":  149, "hogares":   25, "viviendas_ocupadas":   25, "hacinamiento": 6.04},
    "BARRIO SAN SEBASTIAN":          {"poblacion": 2022, "hogares":  455, "viviendas_ocupadas":  437, "hacinamiento": 4.42},
    "BARRIO SANTA LUCIA":            {"poblacion": 2559, "hogares":  593, "viviendas_ocupadas":  588, "hacinamiento": 3.91},
    "BARRIO SUYAPA":                 {"poblacion": 2182, "hogares":  471, "viviendas_ocupadas":  446, "hacinamiento": 4.33},
    "BARRIO TORONDON":               {"poblacion": 3647, "hogares":  920, "viviendas_ocupadas":  909, "hacinamiento": 3.57},
    "BARRIO MATA DE CANA":           {"poblacion":  884, "hogares":  208, "viviendas_ocupadas":  204, "hacinamiento": 4.02},
    # ── Colonias ────────────────────────────────────────────────────────────────
    "COL. 1 DE MAYO":                {"poblacion": 4385, "hogares":  916, "viviendas_ocupadas":  859, "hacinamiento": 4.57},
    "COL. 21 DE ABRIL":              {"poblacion": 5781, "hogares": 1320, "viviendas_ocupadas": 1264, "hacinamiento": 3.90},
    "COL. 2 DE MAYO":                {"poblacion": 2717, "hogares":  589, "viviendas_ocupadas":  585, "hacinamiento": 4.09},
    "COL. 22 DE FEBRERO":            {"poblacion":  115, "hogares":   26, "viviendas_ocupadas":   23, "hacinamiento": 3.51},
    "COL. 3 CAMINOS":                {"poblacion": 1368, "hogares":  346, "viviendas_ocupadas":  337, "hacinamiento": 3.54},
    "COL. AGRICOLA EL JARIN":        {"poblacion":  759, "hogares":  170, "viviendas_ocupadas":  160, "hacinamiento": 3.99},
    "COL. AGRICOLA EL JARIN II":     {"poblacion":  239, "hogares":   50, "viviendas_ocupadas":   47, "hacinamiento": 3.99},
    "COL. BOQUIN":                   {"poblacion": 1968, "hogares":  419, "viviendas_ocupadas":  388, "hacinamiento": 4.31},
    "COL. BRISA DE SUYAPA":          {"poblacion": 1236, "hogares":  272, "viviendas_ocupadas":  266, "hacinamiento": 3.92},
    "COL. BRISAS DE ALTAMIRA":       {"poblacion": 3330, "hogares":  708, "viviendas_ocupadas":  703, "hacinamiento": 4.32},
    "COL. BRISAS DEL HUMUYA #1":     {"poblacion": 1098, "hogares":  249, "viviendas_ocupadas":  246, "hacinamiento": 3.51},
    "COL. C.G.T.":                   {"poblacion": 1510, "hogares":  346, "viviendas_ocupadas":  331, "hacinamiento": 3.77},
    "COL. CARLOS MIRANDA":           {"poblacion":  119, "hogares":   21, "viviendas_ocupadas":   21, "hacinamiento": 4.11},
    "COL. CENTENARIO":               {"poblacion":  147, "hogares":   34, "viviendas_ocupadas":   34, "hacinamiento": 3.69},
    "COL. CONCEPCION":               {"poblacion":  298, "hogares":   58, "viviendas_ocupadas":   58, "hacinamiento": 4.08},
    "COL. DEL VALLE":                {"poblacion":  757, "hogares":  169, "viviendas_ocupadas":  167, "hacinamiento": 4.42},
    "COL. EL INVA":                  {"poblacion":  490, "hogares":  108, "viviendas_ocupadas":   95, "hacinamiento": 4.45},
    "COL. ESCOTO":                   {"poblacion":  470, "hogares":   94, "viviendas_ocupadas":   89, "hacinamiento": 3.55},
    "COL. ESPIRITU SANTO":           {"poblacion":  789, "hogares":  200, "viviendas_ocupadas":  197, "hacinamiento": 3.13},
    "COL. FIALLOS":                  {"poblacion": 2362, "hogares":  508, "viviendas_ocupadas":  495, "hacinamiento": 3.93},
    "COL. FRANCISCO MORAZAN":        {"poblacion": 1326, "hogares":  266, "viviendas_ocupadas":  265, "hacinamiento": 4.10},
    "COL. FUERZAS ARMADAS":          {"poblacion": 2508, "hogares":  560, "viviendas_ocupadas":  542, "hacinamiento": 3.80},
    "COL. IVAN BETANCOURT":          {"poblacion": 2506, "hogares":  534, "viviendas_ocupadas":  511, "hacinamiento": 4.08},
    "COL. JARIN":                    {"poblacion":   91, "hogares":   22, "viviendas_ocupadas":   21, "hacinamiento": 3.03},
    "COL. JAZMINES DEL VALLE":       {"poblacion":  509, "hogares":  114, "viviendas_ocupadas":  112, "hacinamiento": 4.36},
    "COL. JULIO CESAR PINTO":        {"poblacion":  469, "hogares":  102, "viviendas_ocupadas":  102, "hacinamiento": 4.00},
    "COL. LAZOS DE AMISTAD":         {"poblacion":  914, "hogares":  187, "viviendas_ocupadas":  172, "hacinamiento": 4.82},
    "COL. LOS ALAMOS":               {"poblacion":  236, "hogares":   44, "viviendas_ocupadas":   42, "hacinamiento": 5.57},
    "COL. LOS PINOS":                {"poblacion":   60, "hogares":   14, "viviendas_ocupadas":   12, "hacinamiento": 3.80},
    "COL. MAZZARELA":                {"poblacion":  376, "hogares":   82, "viviendas_ocupadas":   76, "hacinamiento": 4.24},
    "COL. MEJICAPA":                 {"poblacion":  335, "hogares":   87, "viviendas_ocupadas":   87, "hacinamiento": 2.98},
    "COL. MEJORES ALIMENTOS":        {"poblacion":  418, "hogares":   96, "viviendas_ocupadas":   96, "hacinamiento": 3.42},
    "COL. MILAGRO DE DIOS":          {"poblacion": 1866, "hogares":  400, "viviendas_ocupadas":  367, "hacinamiento": 4.56},
    "COL. MIRAVALLE":                {"poblacion":  172, "hogares":   40, "viviendas_ocupadas":   40, "hacinamiento": 3.73},
    "COL. NUEVA COMAYAGUA II":       {"poblacion":  399, "hogares":   72, "viviendas_ocupadas":   70, "hacinamiento": 4.20},
    "COL. NUEVA ESPERANZA":          {"poblacion":  770, "hogares":  176, "viviendas_ocupadas":  169, "hacinamiento": 3.71},
    "COL. NUEVA VALLADOLID":         {"poblacion": 2892, "hogares":  650, "viviendas_ocupadas":  620, "hacinamiento": 3.90},
    "COL. PIEDRAS BONITAS":          {"poblacion":  850, "hogares":  191, "viviendas_ocupadas":  191, "hacinamiento": 4.20},
    "COL. PIEDRAS BONITAS NORTE":    {"poblacion":  705, "hogares":  160, "viviendas_ocupadas":  155, "hacinamiento": 3.79},
    "COL. SAN CARLOS":               {"poblacion":  199, "hogares":   38, "viviendas_ocupadas":   32, "hacinamiento": 6.21},
    "COL. SAN FRANCISCO":            {"poblacion":  606, "hogares":  135, "viviendas_ocupadas":  135, "hacinamiento": 4.49},
    "COL. SAN JUAN":                 {"poblacion": 1193, "hogares":  218, "viviendas_ocupadas":  208, "hacinamiento": 4.90},
    "COL. SAN MARTIN":               {"poblacion":  307, "hogares":   67, "viviendas_ocupadas":   66, "hacinamiento": 3.21},
    "COL. SAN MIGUEL":               {"poblacion": 1056, "hogares":  245, "viviendas_ocupadas":  237, "hacinamiento": 4.36},
    "COL. SAN MIGUEL #2":            {"poblacion":  518, "hogares":  122, "viviendas_ocupadas":  120, "hacinamiento": 4.32},
    "COL. SITRAHMEDYS":              {"poblacion":  385, "hogares":   83, "viviendas_ocupadas":   81, "hacinamiento": 3.90},
    "COL. SITRA INCEHSA":            {"poblacion":  195, "hogares":   48, "viviendas_ocupadas":   48, "hacinamiento": 3.22},
    "COL. VALENTIN SUAREZ":          {"poblacion":  127, "hogares":   27, "viviendas_ocupadas":   27, "hacinamiento": 3.43},
    "COL. VILLA DEL RIO":            {"poblacion":  795, "hogares":  159, "viviendas_ocupadas":  155, "hacinamiento": 4.54},
    "COL. VILLEDA BERMUDEZ":         {"poblacion":  219, "hogares":   47, "viviendas_ocupadas":   47, "hacinamiento": 3.93},
    "COL. VISTAS DEL VALLE":         {"poblacion":  348, "hogares":   69, "viviendas_ocupadas":   69, "hacinamiento": 4.20},
    # ── Barrios / Sectores periféricos ──────────────────────────────────────────
    "BO. LA GUAMA":                  {"poblacion":  460, "hogares":  112, "viviendas_ocupadas":  112, "hacinamiento": 4.04},
    "BO. LINCOLN COLEMAN":            {"poblacion":  627, "hogares":  126, "viviendas_ocupadas":  119, "hacinamiento": 4.01},
    "BO. LOS ALMENDROS":             {"poblacion":  967, "hogares":  204, "viviendas_ocupadas":  204, "hacinamiento": 3.67},
    "BO. VISTA HERMOSA":             {"poblacion":  215, "hogares":   42, "viviendas_ocupadas":   40, "hacinamiento": 3.53},
    "BRISAS DE ORIENTE":             {"poblacion":  221, "hogares":   51, "viviendas_ocupadas":   48, "hacinamiento": 4.39},
    "BRISAS DEL VALLE":              {"poblacion":   24, "hogares":    4, "viviendas_ocupadas":    4, "hacinamiento": 6.32},
    "JARDINES DE CAPIRO":            {"poblacion":  234, "hogares":   49, "viviendas_ocupadas":   44, "hacinamiento": 4.21},
    "COLONIA LA TEJERA":                     {"poblacion":  124, "hogares":   29, "viviendas_ocupadas":   29, "hacinamiento": 3.39},
    "COL. LAS CAÑAS":                     {"poblacion":  273, "hogares":   74, "viviendas_ocupadas":   74, "hacinamiento": 2.84},
    "LOMAS DEL CARMEN":              {"poblacion":   92, "hogares":   16, "viviendas_ocupadas":   16, "hacinamiento": 5.01},
    "LOMAS DEL RIO":                 {"poblacion": 2483, "hogares":  562, "viviendas_ocupadas":  546, "hacinamiento": 3.78},
    "RES. LOS LAURELES":                  {"poblacion":  176, "hogares":   41, "viviendas_ocupadas":   40, "hacinamiento": 3.20},
    "LOT. LIRIO DEL VALLE":          {"poblacion":  151, "hogares":   31, "viviendas_ocupadas":   30, "hacinamiento": 5.03},
    "LOT. LOS ANGELES":              {"poblacion":  146, "hogares":   42, "viviendas_ocupadas":   40, "hacinamiento": 3.13},
    "LOT. MONTE VERDE":              {"poblacion":   69, "hogares":   15, "viviendas_ocupadas":   15, "hacinamiento": 4.57},
    "LOT. SAAVEDRA":                 {"poblacion":  498, "hogares":  127, "viviendas_ocupadas":  120, "hacinamiento": 3.79},
    "PRADOS UNIVERSITARIOS":         {"poblacion":  703, "hogares":  140, "viviendas_ocupadas":  137, "hacinamiento": 5.02},
    "RES. FRANCISCO MORAZAN":        {"poblacion":  117, "hogares":   20, "viviendas_ocupadas":   19, "hacinamiento": 6.25},
    "RES. MANA":                     {"poblacion":   99, "hogares":   19, "viviendas_ocupadas":   17, "hacinamiento": 4.30},
    "RES. MARBELLA":                 {"poblacion":   75, "hogares":   16, "viviendas_ocupadas":   15, "hacinamiento": 4.99},
    "RES. VILLA LA QUINTA":          {"poblacion":  126, "hogares":   30, "viviendas_ocupadas":   30, "hacinamiento": 4.13},
    "RES. VILLA SANTA MARTA":        {"poblacion":  194, "hogares":   39, "viviendas_ocupadas":   38, "hacinamiento": 4.15},
    "RES. VILLAS ALCAZAR":           {"poblacion":   58, "hogares":    7, "viviendas_ocupadas":    7, "hacinamiento": 7.78},
    "ROTARIA":                       {"poblacion":  263, "hogares":   49, "viviendas_ocupadas":   47, "hacinamiento": 4.29},
    "SAN RAFAEL":                    {"poblacion":  756, "hogares":  168, "viviendas_ocupadas":  160, "hacinamiento": 4.23},
    "TR. LAS CANOAS":                {"poblacion":   54, "hogares":   11, "viviendas_ocupadas":   11, "hacinamiento": 4.29},
    "VILLAS DE SANTA MARIA":         {"poblacion":   93, "hogares":   19, "viviendas_ocupadas":   19, "hacinamiento": 4.91},
    "VILLAS MARIA":                  {"poblacion":  368, "hogares":   75, "viviendas_ocupadas":   74, "hacinamiento": 3.68},
    "VILLAS UNIVERSITARIAS":         {"poblacion":  178, "hogares":   34, "viviendas_ocupadas":   32, "hacinamiento": 5.48},
    "9 DE NOVIEMBRE":                {"poblacion":  694, "hogares":  160, "viviendas_ocupadas":  159, "hacinamiento": 3.28},
    "ASERRADERO SANTA MARIA":        {"poblacion":  299, "hogares":   62, "viviendas_ocupadas":   62, "hacinamiento": 4.79},
}

# Población urbana total (suma de Tabla 4)
TOTAL_POBLACION_URBANA: int = sum(b["poblacion"] for b in BARRIOS_COMAYAGUA.values())
